import styles from "./PanelHash.module.scss"
import { useContext } from "react"
import { faRotate } from "@fortawesome/free-solid-svg-icons"
import { PanelGroup } from "./PanelGroup"
import {
  BaseInput,
  BaseButton,
  IconButton,
} from "components/FxParams/BaseInput"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { generateFxHash } from "utils/hash"

interface Props {
  hash: string
  onChangeHash: (h: string) => void
}

export function PanelHash(props: Props) {
  const { hash, onChangeHash } = props
  const handleChange = (e: any) => {
    onChangeHash(e.target.value)
  }
  const handleRefresh = () => {
    onChangeHash(generateFxHash())
  }

  return (
    <PanelGroup
      title="Current seed"
      description="The seed is generated by the signing module. Here you can test
      different seeds with your params."
    >
      <div className={styles.hashControls}>
        <BaseInput
          type="text"
          value={hash}
          onChange={handleChange}
          className={styles.hashInput}
        />
        <IconButton onClick={handleRefresh}>
          <FontAwesomeIcon icon={faRotate} />
        </IconButton>
      </div>
    </PanelGroup>
  )
}
